list_of_airlines=["AI","SJ","JA","EM","AA"]
new_list=list_of_airlines[1:4]
print(new_list)
new_list=list_of_airlines[-4:-1]
print(new_list)
new_list=list_of_airlines[1:]
print(new_list)
new_list=list_of_airlines[:2]
print(new_list)
new_list=list_of_airlines[:-2]
print(new_list)
new_list=list_of_airlines[-5:]
print(new_list)
new_list=list_of_airlines[1:-2]
print(new_list)
new_list=list_of_airlines[:5]
print(new_list)
new_list=list_of_airlines[-6:]
print(new_list)
new_list=list_of_airlines[-6:2]
print(new_list)
new_list=list_of_airlines[-3:5]
print(new_list)
